import { NextRequest, NextResponse } from "next/server";
import { z } from "zod";
import { planVimaxStory } from "@/lib/anthropic";
import type { StockPhoto } from "@/lib/stock";
import { applyStyle, findImageModel, findStylePreset } from "@/lib/catalog";
import { createTask, waitForTask } from "@/lib/kie";

export const runtime = "nodejs";
export const dynamic = "force-dynamic";

const Body = z.object({
  idea: z.string().min(5).max(2000),
  sceneCount: z.number().int().min(2).max(12).optional(),
  imageModelId: z.string().min(1),
  styleId: z.string().max(60).optional(),
});

export type VimaxScene = {
  text: string;
  keywords: string;
  alt?: string;
  selected: StockPhoto | null;
  /** Surfaced to the UI when image generation fails so the user can see why
   *  the slot is empty. Null/undefined means success or not-yet-attempted. */
  imageError?: string;
};

export type VimaxPlanResponse = {
  title: string;
  scenes: VimaxScene[];
};

/**
 * POST /api/vimax/plan
 *
 * The ViMax-style idea→video pipeline:
 *   1. Claude expands the idea into a {title, scenes[text, keywords]} plan.
 *   2. Per scene, in parallel, generate a frame via the chosen Kie.ai image
 *      model with the user's style preset appended to the prompt.
 *
 * Per-scene Veo clip generation (the full ViMax pipeline) requires
 * worker-side orchestration to avoid HTTP timeouts and is intentionally
 * left to the longform job that this plan feeds into.
 */
export async function POST(req: NextRequest) {
  let body: unknown;
  try {
    body = await req.json();
  } catch {
    return NextResponse.json({ error: "Invalid JSON" }, { status: 400 });
  }
  const parsed = Body.safeParse(body);
  if (!parsed.success) {
    return NextResponse.json(
      { error: "Invalid request", issues: parsed.error.issues },
      { status: 400 },
    );
  }
  const { idea, sceneCount, imageModelId, styleId } = parsed.data;
  const model = findImageModel(imageModelId);
  if (!model) {
    return NextResponse.json({ error: `Unknown image model: ${imageModelId}` }, { status: 400 });
  }
  const styleLabel = findStylePreset(styleId)?.label ?? "AI";
  const attribution = `Generated by ${model.label} · ${styleLabel}`;

  let plan: Awaited<ReturnType<typeof planVimaxStory>>;
  try {
    plan = await planVimaxStory(idea, sceneCount ?? 6);
  } catch (err) {
    const message = err instanceof Error ? err.message : "Storyboard planning failed";
    return NextResponse.json({ error: message }, { status: 502 });
  }

  const scenes: VimaxScene[] = await Promise.all(
    plan.scenes.map(async (s, idx) => {
      try {
        const basePrompt = `Cinematic 16:9 establishing shot. Subject: ${s.keywords}. ${s.alt ?? ""}`;
        const prompt = applyStyle(basePrompt, styleId);
        const taskId = await createTask({
          model: model.slug,
          input: { prompt, aspectRatio: "16:9" },
        });
        const { urls } = await waitForTask(taskId, ["image"]);
        const url = urls[0];
        if (!url) {
          return {
            ...s,
            selected: null,
            imageError: `Kie task ${taskId} returned no image URL.`,
          };
        }
        const selected: StockPhoto = {
          id: `vimax-${idx}-${Date.now()}`,
          provider: "ai",
          width: 1920,
          height: 1080,
          url,
          thumbUrl: url,
          photographer: model.label,
          pageUrl: url,
          alt: attribution,
        };
        return { ...s, selected };
      } catch (err) {
        const message = err instanceof Error ? err.message : String(err);
        console.warn(`[vimax] scene ${idx + 1} image gen failed: ${message}`);
        return { ...s, selected: null, imageError: message };
      }
    }),
  );

  const response: VimaxPlanResponse = { title: plan.title, scenes };
  return NextResponse.json(response);
}
