import { NextRequest, NextResponse } from "next/server";
import { z } from "zod";
import type { StockPhoto } from "@/lib/stock";
import { applyStyle, findImageModel, findStylePreset } from "@/lib/catalog";
import { createTask, waitForTask } from "@/lib/kie";
import { withUser } from "@/lib/route-auth";

export const runtime = "nodejs";
export const dynamic = "force-dynamic";

const Body = z.object({
  imageModelId: z.string().min(1).optional(),
  /** Free-form Kie marketplace slug, e.g. "google/nano-banana-pro". When
   *  provided, overrides imageModelId so the user can paste a slug straight
   *  from their Kie dashboard without waiting for a catalog update. */
  customSlug: z.string().min(1).max(120).optional(),
  styleId: z.string().max(60).optional(),
  aspect: z.enum(["9:16", "1:1", "16:9"]).optional(),
  keywords: z.string().min(1).max(400),
  alt: z.string().max(400).optional(),
});

const ASPECT_TO_PIXELS = {
  "9:16": { w: 1080, h: 1920 },
  "1:1": { w: 1080, h: 1080 },
  "16:9": { w: 1920, h: 1080 },
} as const;

/**
 * POST /api/youtube/image
 * Render a single scene frame on demand. Used by the YouTube wizard's
 * step-4 review to render images per-scene with bounded concurrency, and to
 * power the Retry button when a scene's image fails.
 *
 * Mirrors /api/vimax/image but accepts the wizard's aspect ratio so 9:16 /
 * 1:1 / 16:9 outputs all get appropriately framed source images.
 */
export async function POST(req: NextRequest) {
  return withUser(async () => {
  let body: unknown;
  try {
    body = await req.json();
  } catch {
    return NextResponse.json({ error: "Invalid JSON" }, { status: 400 });
  }
  const parsed = Body.safeParse(body);
  if (!parsed.success) {
    return NextResponse.json(
      { error: "Invalid request", issues: parsed.error.issues },
      { status: 400 },
    );
  }
  const { imageModelId, customSlug, styleId, keywords, alt, aspect = "16:9" } = parsed.data;

  let slug: string;
  let label: string;
  if (customSlug && customSlug.trim()) {
    slug = customSlug.trim();
    label = `Custom (${slug})`;
  } else {
    if (!imageModelId) {
      return NextResponse.json({ error: "Missing imageModelId or customSlug" }, { status: 400 });
    }
    const model = findImageModel(imageModelId);
    if (!model) {
      return NextResponse.json({ error: `Unknown image model: ${imageModelId}` }, { status: 400 });
    }
    slug = model.slug;
    label = model.label;
  }

  const pixels = ASPECT_TO_PIXELS[aspect];

  try {
    const basePrompt = `Editorial ${aspect} establishing shot for a YouTube scene. Subject: ${keywords}. ${alt ?? ""}`.trim();
    const prompt = applyStyle(basePrompt, styleId);
    // Send both casings — Kie marketplace models disagree (Seedance/Kling use
    // camelCase; Z-Image uses snake_case). Models ignore unknown keys.
    const taskId = await createTask({
      model: slug,
      input: {
        prompt,
        aspectRatio: aspect,
        aspect_ratio: aspect,
        nsfw_checker: true,
      },
    });
    const { urls } = await waitForTask(taskId, ["image"]);
    const url = urls[0];
    if (!url) {
      return NextResponse.json(
        { error: `Kie task ${taskId} returned no image URL.` },
        { status: 502 },
      );
    }
    const styleLabel = findStylePreset(styleId)?.label ?? "AI";
    const selected: StockPhoto = {
      id: `youtube-${Date.now()}-${Math.random().toString(36).slice(2, 8)}`,
      provider: "ai",
      width: pixels.w,
      height: pixels.h,
      url,
      thumbUrl: url,
      photographer: label,
      pageUrl: url,
      alt: `Generated by ${label} · ${styleLabel}`,
    };
    return NextResponse.json({ selected });
  } catch (err) {
    const message = err instanceof Error ? err.message : String(err);
    return NextResponse.json({ error: `[slug=${slug}] ${message}` }, { status: 502 });
  }
  });
}
