import { NextRequest, NextResponse } from "next/server";
import { z } from "zod";
import type { StockPhoto } from "@/lib/stock";
import { applyStyle, findImageModel, findStylePreset } from "@/lib/catalog";
import { createTask, waitForTask } from "@/lib/kie";
import { withUser } from "@/lib/route-auth";

export const runtime = "nodejs";
export const dynamic = "force-dynamic";

const Body = z.object({
  imageModelId: z.string().min(1).optional(),
  /** Free-form Kie marketplace slug, e.g. "google/nano-banana-pro". When
   *  provided, overrides imageModelId so the user can paste a slug straight
   *  from their Kie dashboard without waiting for a catalog update. */
  customSlug: z.string().min(1).max(120).optional(),
  styleId: z.string().max(60).optional(),
  keywords: z.string().min(1).max(400),
  alt: z.string().max(400).optional(),
});

/**
 * POST /api/vimax/image
 * Render a single scene frame on demand. Used by the ViMax page's
 * "Retry image" button so the user can re-roll one scene without re-running
 * Claude's storyboard.
 */
export async function POST(req: NextRequest) {
  return withUser(async () => {
  let body: unknown;
  try {
    body = await req.json();
  } catch {
    return NextResponse.json({ error: "Invalid JSON" }, { status: 400 });
  }
  const parsed = Body.safeParse(body);
  if (!parsed.success) {
    return NextResponse.json(
      { error: "Invalid request", issues: parsed.error.issues },
      { status: 400 },
    );
  }
  const { imageModelId, customSlug, styleId, keywords, alt } = parsed.data;

  let slug: string;
  let label: string;
  if (customSlug && customSlug.trim()) {
    slug = customSlug.trim();
    label = `Custom (${slug})`;
  } else {
    if (!imageModelId) {
      return NextResponse.json({ error: "Missing imageModelId or customSlug" }, { status: 400 });
    }
    const model = findImageModel(imageModelId);
    if (!model) {
      return NextResponse.json({ error: `Unknown image model: ${imageModelId}` }, { status: 400 });
    }
    slug = model.slug;
    label = model.label;
  }

  try {
    const basePrompt = `Cinematic 16:9 establishing shot. Subject: ${keywords}. ${alt ?? ""}`;
    const prompt = applyStyle(basePrompt, styleId);
    // Kie's marketplace models disagree on input casing — Seedance/Kling use
    // camelCase (aspectRatio), Z-Image uses snake_case (aspect_ratio). Send
    // both: any model that doesn't recognize a key just ignores it.
    const taskId = await createTask({
      model: slug,
      input: {
        prompt,
        aspectRatio: "16:9",
        aspect_ratio: "16:9",
        nsfw_checker: true,
      },
    });
    const { urls } = await waitForTask(taskId, ["image"]);
    const url = urls[0];
    if (!url) {
      return NextResponse.json(
        { error: `Kie task ${taskId} returned no image URL.` },
        { status: 502 },
      );
    }
    const styleLabel = findStylePreset(styleId)?.label ?? "AI";
    const selected: StockPhoto = {
      id: `vimax-${Date.now()}`,
      provider: "ai",
      width: 1920,
      height: 1080,
      url,
      thumbUrl: url,
      photographer: label,
      pageUrl: url,
      alt: `Generated by ${label} · ${styleLabel}`,
    };
    return NextResponse.json({ selected });
  } catch (err) {
    const message = err instanceof Error ? err.message : String(err);
    return NextResponse.json(
      { error: `[slug=${slug}] ${message}` },
      { status: 502 },
    );
  }
  });
}
