import { NextRequest, NextResponse } from "next/server";
import { z } from "zod";
import type { StockPhoto } from "@/lib/stock";
import { applyStyle, findImageModel, findStylePreset } from "@/lib/catalog";
import { createTask, waitForTask } from "@/lib/kie";

export const runtime = "nodejs";
export const dynamic = "force-dynamic";

const Body = z.object({
  imageModelId: z.string().min(1),
  styleId: z.string().max(60).optional(),
  keywords: z.string().min(1).max(400),
  alt: z.string().max(400).optional(),
});

/**
 * POST /api/vimax/image
 * Render a single scene frame on demand. Used by the ViMax page's
 * "Retry image" button so the user can re-roll one scene without re-running
 * Claude's storyboard.
 */
export async function POST(req: NextRequest) {
  let body: unknown;
  try {
    body = await req.json();
  } catch {
    return NextResponse.json({ error: "Invalid JSON" }, { status: 400 });
  }
  const parsed = Body.safeParse(body);
  if (!parsed.success) {
    return NextResponse.json(
      { error: "Invalid request", issues: parsed.error.issues },
      { status: 400 },
    );
  }
  const { imageModelId, styleId, keywords, alt } = parsed.data;
  const model = findImageModel(imageModelId);
  if (!model) {
    return NextResponse.json({ error: `Unknown image model: ${imageModelId}` }, { status: 400 });
  }

  try {
    const basePrompt = `Cinematic 16:9 establishing shot. Subject: ${keywords}. ${alt ?? ""}`;
    const prompt = applyStyle(basePrompt, styleId);
    const taskId = await createTask({
      model: model.slug,
      input: { prompt, aspectRatio: "16:9" },
    });
    const { urls } = await waitForTask(taskId, ["image"]);
    const url = urls[0];
    if (!url) {
      return NextResponse.json(
        { error: `Kie task ${taskId} returned no image URL.` },
        { status: 502 },
      );
    }
    const styleLabel = findStylePreset(styleId)?.label ?? "AI";
    const selected: StockPhoto = {
      id: `vimax-${Date.now()}`,
      provider: "ai",
      width: 1920,
      height: 1080,
      url,
      thumbUrl: url,
      photographer: model.label,
      pageUrl: url,
      alt: `Generated by ${model.label} · ${styleLabel}`,
    };
    return NextResponse.json({ selected });
  } catch (err) {
    const message = err instanceof Error ? err.message : String(err);
    return NextResponse.json({ error: message }, { status: 502 });
  }
}
