import { NextRequest, NextResponse } from "next/server";
import { z } from "zod";
import { planLongformScenes } from "@/lib/anthropic";
import { searchPexels, type StockPhoto } from "@/lib/stock";
import { applyStyle, findImageModel, findStylePreset } from "@/lib/catalog";
import { createTask, waitForTask } from "@/lib/kie";

export const runtime = "nodejs";
export const dynamic = "force-dynamic";

const Body = z.object({
  script: z.string().min(20).max(20_000),
  imageSource: z.enum(["pexels", "ai"]).optional(),
  imageModelId: z.string().max(100).optional(),
  styleId: z.string().max(60).optional(),
});

export type PlannedScene = {
  text: string;
  keywords: string;
  alt?: string;
  selected: StockPhoto | null;
};

export type PlanResponse = {
  title: string;
  scenes: PlannedScene[];
};

/**
 * POST /api/youtube/plan
 * Body: { script, imageSource?, imageModelId?, styleId? }
 *
 * Pipeline:
 *   1. Claude turns the script into { title, scenes[{text, keywords}] }
 *   2. For each scene, attach a `selected` image:
 *        - imageSource="pexels" (default): top Pexels match for keywords
 *        - imageSource="ai":               Kie.ai image task driven by the
 *                                          scene's keywords + chosen style
 *      Failures degrade — `selected` stays null so the user can retry per-scene.
 */
export async function POST(req: NextRequest) {
  let body: unknown;
  try {
    body = await req.json();
  } catch {
    return NextResponse.json({ error: "Invalid JSON" }, { status: 400 });
  }
  const parsed = Body.safeParse(body);
  if (!parsed.success) {
    return NextResponse.json(
      { error: "Invalid request", issues: parsed.error.issues },
      { status: 400 },
    );
  }

  const { script, imageSource = "pexels", imageModelId, styleId } = parsed.data;
  const aiModel = imageSource === "ai" && imageModelId ? findImageModel(imageModelId) : undefined;
  if (imageSource === "ai" && !aiModel) {
    return NextResponse.json(
      { error: `Unknown or missing image model for AI generation: ${imageModelId}` },
      { status: 400 },
    );
  }

  let plan: Awaited<ReturnType<typeof planLongformScenes>>;
  try {
    plan = await planLongformScenes(script);
  } catch (err) {
    const message = err instanceof Error ? err.message : "Scene planning failed";
    return NextResponse.json({ error: message }, { status: 502 });
  }

  const styleLabel = findStylePreset(styleId)?.label ?? "AI";
  const aiAttribution = aiModel ? `Generated by ${aiModel.label} · ${styleLabel}` : "";

  const scenes: PlannedScene[] = await Promise.all(
    plan.scenes.map(async (s, idx) => {
      try {
        if (aiModel) {
          const basePrompt = `Editorial 16:9 establishing shot for a YouTube scene. Subject: ${s.keywords}. Mood from script: ${s.text.slice(0, 240)}`;
          const prompt = applyStyle(basePrompt, styleId);
          const taskId = await createTask({
            model: aiModel.slug,
            input: {
              prompt,
              aspectRatio: "16:9",
              aspect_ratio: "16:9",
              nsfw_checker: true,
            },
          });
          const { urls } = await waitForTask(taskId, ["image"]);
          const url = urls[0];
          if (!url) return { ...s, selected: null };
          const selected: StockPhoto = {
            id: `ai-${idx}-${Date.now()}`,
            provider: "ai",
            width: 1920,
            height: 1080,
            url,
            thumbUrl: url,
            photographer: aiModel.label,
            pageUrl: url,
            alt: aiAttribution,
          };
          return { ...s, selected };
        }
        const photos = await searchPexels({
          query: s.keywords,
          orientation: "landscape",
          perPage: 4,
        });
        return { ...s, selected: photos[0] ?? null };
      } catch (err) {
        console.warn(
          `[plan] image fetch failed for scene ${idx + 1}: ${(err as Error).message}`,
        );
        return { ...s, selected: null };
      }
    }),
  );

  const response: PlanResponse = { title: plan.title, scenes };
  return NextResponse.json(response);
}
